name: Main CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  

env:
  CI: false
  env_main: ${{secrets.ENV_MAIN}}

jobs:
  docker_build:
    name: build docker images and push to DH
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: create environment file
        run: |
          touch ./.env && echo "$env_main" >> ./.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Image
      - name: build && push Client
        id: build-push-client
        uses: docker/build-push-action@v5
        with:
          context: client
          platforms: linux/amd64
          file: client/Dockerfile
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: esatya/rahat-offramp:main